### ISSUE TITLE
"Unknown Error" during authentificator registration

### ISSUE THREAD

**Issue by tobiasd** [cvc-digital/typo3-webauthn#9]
I tried the extension with a minimal Typo3 v9.5.15 composer installation using a Nitrokey FIDO2 stick as token. When trying to register the token for authentication I get an error

> Error : Unknown error occurred

The reason for the error was, that I had  tested the extension in a qemu VM on my notebook to not overload the production system with unneeded extensions for testing. Later I realized that the browser does not engage in WebAuthn negotiations, as long as the requesting page was not using HTTPS, which was not the case with the VM I used.

I think it would be helpful when there was not the mention of an unknown error, but a hint about WebAuthn requiring an secured connection. Though I don't know how feasible this is.

Using the extension with the Nitrokey on the production server with HTTPS enabled solved the problem entirely.

**Comment by markuspoerschke** [comment]
Since version 1.2.0, the backend user sees a propper error message when they try to register their key if the connection is not secured using HTTPS.

The README still needs a hint, that the extension works only with HTTPS.

The Login also needs the same warning. Currently the login stucks at non HTTPS connections.

We are using DDEV for development. Therefore we always have a valid HTTPS connection during development on our work machines.

**Comment by tobiasd** [comment]
Thanks for the quick reply :)
